# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annotation', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_name', models.CharField(max_length=500)),
                ('lat_name', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=3000)),
                ('sec_measures', models.CharField(max_length=2000)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='reservations',
            field=models.ManyToManyField(to='plants.Reservation'),
        ),
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Status'),
        ),
    ]
